use crate::{Error, Validator};

/// Validation behavior implemented manually or generated by `#[derive(Validate)]`.
pub trait Validate {
    /// Validates this value with the provided validator configuration.
    fn validate(&self, validator: &Validator) -> Result<(), Error>;
}

#[doc(hidden)]
#[allow(missing_docs)]
pub trait Selective {
    #[doc(hidden)]
    fn __validate_with_context(
        &self,
        validator: &Validator,
        context: &crate::__private::Context<'_>,
    ) -> Result<(), Error>;
}
